package com.gard.testbed.engine.eventBus.events;


import com.gard.testbed.engine.petrinet.Transition;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Chris on 11/03/2016..
 * Event generated by ActivityManager
 */
public class ActivityEvent extends Event{

    private List<Transition> activeTransitions = new ArrayList<>();

    public ActivityEvent(String target, MessageType type, String message) {
        super(target, type, message);
    }

    public ActivityEvent(String target, MessageType type, String message, List<Transition> activeTransitions) {
        super(target, type, message);
        this.activeTransitions = activeTransitions;
    }

    public List<Transition> getActiveTransitions(){
        return activeTransitions;
    }


}
