package com.gard.testbed.engine.eventBus.events;


/**
 * Created by Chris on 11/03/2016..
 * Event generated by UI
 */
public class UiEvent extends Event {

    public UiEvent(String target, MessageType type, String message) {
        super(target, type, message);
    }
}
